import { KoiApi } from "./api.js?v=20260928";
const pickerCss=document.createElement("link"); pickerCss.rel="stylesheet"; pickerCss.href="picker.css?v=20260928"; document.head.append(pickerCss);
const params=new URLSearchParams(location.search), project=params.get("project")||sessionStorage.getItem("koi-mortal-project")||"";
let primary=parsePaper(params.get("primary")), reviewer=parsePaper(params.get("reviewer")), timer=null, runId=null;
let importedLibrary=[]; try { importedLibrary=JSON.parse(sessionStorage.getItem("koi-mortal-library")||"[]"); } catch { importedLibrary=[]; }
function parsePaper(raw){if(!raw)return null;try{return JSON.parse(decodeURIComponent(raw))}catch{return null}}
const $=id=>document.getElementById(id);
document.querySelectorAll(".sprite")[0].innerHTML='<img src="assets/scientist-fight.gif" alt="Защитник" />';
document.querySelectorAll(".sprite")[1].innerHTML='<img src="assets/grandma-scientist-fight.gif" alt="Критик" />';
document.querySelectorAll(".sprite img").forEach(img=>{img.style.width="180px";img.style.height="150px";img.style.objectFit="contain";img.style.imageRendering="pixelated"});
function render(){if(primary){$("primary-title").textContent=primary.title||primary.arxiv_url||"Основная статья";$("primary-meta").textContent=primary.authors||primary.abstract||"Основная работа"}if(reviewer){$("reviewer-title").textContent=reviewer.title||reviewer.arxiv_url||"Статья ревьювера";$("reviewer-meta").textContent=reviewer.authors||reviewer.abstract||"Контекст критики"}}
async function pick(which){
  let data;
  try { data=await KoiApi.listLibraryPapers(200); } catch(e) { alert(`Не удалось загрузить библиотеку: ${e.message}`); return; }
  const papers=importedLibrary.length ? importedLibrary : (data.papers||[]), overlay=document.createElement("div"); overlay.className="paper-picker-overlay";
  overlay.innerHTML=`<div class="paper-picker" role="dialog" aria-modal="true"><button class="picker-close" aria-label="Закрыть">×</button><p class="eyebrow">${which==="primary"?"ОСНОВНАЯ СТАТЬЯ":"СТАТЬЯ РЕВЬЮВЕРА"}</p><h2>Выберите статью из библиотеки</h2><p class="picker-hint">Здесь отображаются статьи из локальной библиотеки, в том числе импортированные из Zotero.</p><input class="picker-search" placeholder="Поиск по названию и авторам"><div class="picker-list"></div></div>`;
  document.body.append(overlay); const list=overlay.querySelector(".picker-list"), search=overlay.querySelector(".picker-search");
  const draw=()=>{const q=search.value.toLowerCase();list.innerHTML=papers.filter(p=>`${p.title||""} ${p.authors||""}`.toLowerCase().includes(q)).map((p,i)=>`<button class="picker-paper" data-index="${i}"><b>${p.title||"Без названия"}</b><small>${p.authors||"Авторы не указаны"}</small></button>`).join("")||`<p class="empty">Статьи не найдены. Импортируйте коллекцию через Zotero в разделе литературы.</p>`; list.querySelectorAll("button").forEach(b=>b.onclick=()=>{const p=papers[Number(b.dataset.index)];if(which==="primary")primary=p;else reviewer=p;render();overlay.remove()})};
  search.oninput=draw; overlay.querySelector(".picker-close").onclick=()=>overlay.remove(); overlay.onclick=e=>{if(e.target===overlay)overlay.remove()}; draw(); search.focus();
}
function renderMessages(messages=[]){if(!messages.length)return;$("dialogue-list").innerHTML=messages.map(m=>`<div class="dialogue-card ${m.role||""}"><b>${m.role==="defender"?"Защитник":m.role==="critic"?"Критик":"Судья"} · раунд ${m.round||"—"}</b><p>${m.text||""}</p><small>${(m.evidence||[]).map(e=>`${e.paper||""}, с. ${e.page||"—"}: «${e.quote||""}»`).join(" · ")}</small></div>`).join("");const last=messages[messages.length-1];$("round-number").textContent=last.round||"—";$("round-title").textContent="Живой обмен сообщениями"}
function show(data){renderMessages(data.messages||[]);const result=data.result;if(!result)return;if(result.focus){$("fight-question").value=result.focus;$("fight-question").readOnly=true;$("fight-question").title=result.focus_source==="judge"?"Фокус выбран судьёй после чтения обеих статей":"Фокус задан пользователем"}const rounds=result.rounds||[];$("arena-status").textContent="CLI-агент завершил работу";$("verdict-copy").innerHTML=`<div class="verdict-copy">${result.summary||"Вердикт сформирован."}</div>`}
async function poll(){if(!runId)return;try{const d=await KoiApi.getMortalCombat(project,runId);show(d);if(d.result)clearInterval(timer);else $("arena-status").textContent=`Агенты обмениваются сообщениями… ${(d.messages||[]).length}`;}catch(e){$("arena-status").textContent=e.message}}
$("start-fight").onclick=async()=>{if(!project)return alert("Откройте арену из проекта ResearchOS.");if(!primary||!reviewer)return alert("Нужны две статьи: основная и ревьювера.");try{const d=await KoiApi.stageMortalCombat(project,primary,reviewer,$("fight-question").value);runId=d.run_id;$("arena-status").textContent="CLI-агенты вызваны в Terminal";timer=setInterval(poll,3000);await poll()}catch(e){alert(e.message)}};
document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>pick(b.dataset.pick));$("back-literature").href=`literature.html?project=${encodeURIComponent(project)}`;render();
$("fight-question").title="Оставьте пустым, чтобы судья выбрал фокус после чтения обеих статей";
